name: check_code_quality

on:
  push:
    branches: [ main ]
    paths:
      - "sagemaker_image_builder/**.py"
      - "test/**.py"

  pull_request:
    branches: [ main ]
    paths:
      - "sagemaker_image_builder/**.py"
      - "test/**.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: Check Code Quality
    runs-on: ubuntu-latest
    if: github.repository == 'aws/sagemaker-image-builder'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ./environment.yml
          environment-name: sagemaker-image-builder
          init-shell: bash
      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache
      - name: Activate sagemaker-image-builder
        run: micromamba activate sagemaker-image-builder
      - name: Check style with black
        run: black --line-length=120 --check sagemaker_image_builder test
      - name: Check style with autoflake
        run: autoflake --in-place --expand-star-imports --ignore-init-module-imports --remove-all-unused-imports -rc sagemaker_image_builder test
      - name: Check style with isort
        run: isort --profile black -c sagemaker_image_builder test
